spring:
  application:
    name: online-shop
  main:
    banner-mode: off

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://172.16.15.69:5433/postgres
    username: postgres
    password: 1234

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update  # (validate, update, create, create-drop)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: 172.16.15.69
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8081
  servlet:
    context-path: /api



otp:
  expiration-time: 300  # 5 دقیقه به ثانیه
  max-attempts: 3
  resend-cooldown: 60   # 1 دقیقه به

doc:
  title: Online Shop
  version: @project.version@
  description: Shop For Younger ...
  server:
    url: /api
