greeting:
  message: "hello"

# Datasource configuration
quarkus:
  http:
    port: 9001
    root-path: /api
  index-dependency:
    domain:
      group-id: ir.shop.online
      artifact-id: core-domain
    application:
      group-id: ir.shop.online
      artifact-id: core-application
    infrastructure:
      group-id: ir.shop.online
      artifact-id: core-infrastructure
    presentation:
      group-id: ir.online-shop
      artifact-id: core-presentation


  datasource:
    db-kind: postgresql
    username: postgres
    password: 1234
    jdbc:
      url: jdbc:postgresql://172.16.15.69:5433/postgres
    # اگر می‌خواهید DevServices (Docker) خودکار فعال باشد
    devservices:
      enabled: true

  hibernate-orm:
    # برای ایجاد یا آپدیت جدول‌ها در شروع
    database:
      generation: update
    log:
      sql: true

  # Logging
  log:
    category:
      "io.quarkus.hibernate.orm": DEBUG